os:
  - linux
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "node"
  - "6"
  - "6.1"
  - "5"
  - "4"
before_script:
  - yarn global add ava codecov nyc
script:
  - yarn run cover
after_success: 
  - yarn run report
