os:
  - linux
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "node"
  - "6"
  - "6.1"
  - "5"
  - "4"
  - "iojs"
before_script:
  - npm i -g ava codecov nyc
  - npm i --only=dev
script:
  - npm run cover
after_success: npm run report
matrix:
  allow_failures:
    - node_js: "iojs"
