os:
  - linux
  - osx
language: node_js
notifications:
  email: false
node_js:
  - "node"
  - "7.1"
  - "6.1"
before_script:
  - npm i -g ava codecov nyc
  - npm i
  - npm run build
script:
  - npm run test
  - npm run cover
after_success: 
  - npm run report
