os:
  - linux
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "node"
  - "6"
  - "6.1"
  - "5"
  - "4"
before_script:
  - rm -rf ./node_modules .yarnclean
  - npm cache clean
  - npm i -g ava codecov nyc
  - npm i
  - npm i --only=dev
  - npm run build
script:
  - npm run test
  - npm run cover
after_success: 
  - npm run report
